-- ~/.config/nvim/lua/plugins/transparent.lua
return {
    "xiyaowong/transparent.nvim",
    lazy = false,
    config = function()
        require("transparent").setup({
            groups = {  -- 默认组
                'Normal', 'NormalNC', 'Comment', 'Constant', 'Special',
                'Identifier', 'Statement', 'PreProc', 'Type', 'Underlined',
                'Todo', 'String', 'Function', 'Conditional', 'Repeat',
                'Operator', 'Structure', 'LineNr', 'NonText', 'SignColumn',
                'CursorLine', 'CursorLineNr', 'StatusLine', 'StatusLineNC',
                'EndOfBuffer',
            },
            extra_groups = {  -- 额外组（根据你的输出来）
                'NormalFloat', 'NvimTreeNormal',
                'TelescopeNormal', 'TelescopeBorder', 'MasonNormal',
                'LazyNormal', 'WhichKeyFloat', 'NotifyBackground',
                -- 所有 bufferline 高亮组（根据你的输出来）
                'BufferLineBackground',
                'BufferLineBuffer',
                'BufferLineBufferSelected',
                'BufferLineBufferVisible',
                'BufferLineCloseButton',
                'BufferLineCloseButtonSelected',
                'BufferLineCloseButtonVisible',
                'BufferLineDiagnostic',
                'BufferLineDiagnosticSelected',
                'BufferLineDiagnosticVisible',
                'BufferLineDuplicate',
                'BufferLineDuplicateSelected',
                'BufferLineDuplicateVisible',
                'BufferLineError',
                'BufferLineErrorDiagnostic',
                'BufferLineErrorDiagnosticSelected',
                'BufferLineErrorDiagnosticVisible',
                'BufferLineErrorSelected',
                'BufferLineErrorVisible',
                'BufferLineFill',
                'BufferLineGroupLabel',
                'BufferLineGroupSeparator',
                'BufferLineHint',
                'BufferLineHintDiagnostic',
                'BufferLineHintDiagnosticSelected',
                'BufferLineHintDiagnosticVisible',
                'BufferLineHintSelected',
                'BufferLineHintVisible',
                'BufferLineIndicatorSelected',
                'BufferLineIndicatorVisible',
                'BufferLineInfo',
                'BufferLineInfoDiagnostic',
                'BufferLineInfoDiagnosticSelected',
                'BufferLineInfoDiagnosticVisible',
                'BufferLineInfoSelected',
                'BufferLineInfoVisible',
                'BufferLineModified',
                'BufferLineModifiedSelected',
                'BufferLineModifiedVisible',
                'BufferLineNumbers',
                'BufferLineNumbersSelected',
                'BufferLineNumbersVisible',
                'BufferLineOffsetSeparator',
                'BufferLinePick',
                'BufferLinePickSelected',
                'BufferLinePickVisible',
                'BufferLineSeparator',
                'BufferLineSeparatorSelected',
                'BufferLineSeparatorVisible',
                'BufferLineTab',
                'BufferLineTabClose',
                'BufferLineTabSelected',
                'BufferLineTabSeparator',
                'BufferLineTabSeparatorSelected',
                'BufferLineTruncMarker',
                'BufferLineWarning',
                'BufferLineWarningDiagnostic',
                'BufferLineWarningDiagnosticSelected',
                'BufferLineWarningDiagnosticVisible',
                'BufferLineWarningSelected',
                'BufferLineWarningVisible',
            },
        })
    end,
}
